// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using zadanie2;

namespace zadanie2.Migrations
{
    [DbContext(typeof(Program.BloggingContext))]
    partial class BloggingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("zadanie2.Program+ANIEM", b =>
                {
                    b.Property<int>("aniemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ILOSCODCINKOW")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NAZWA")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("mediaID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("sezonID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("tagiID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("tworcaID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("tworcyID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("aniemID");

                    b.HasIndex("mediaID");

                    b.HasIndex("sezonID");

                    b.HasIndex("tagiID");

                    b.HasIndex("tworcaID");

                    b.ToTable("ANIEM");
                });

            modelBuilder.Entity("zadanie2.Program+MEDIA", b =>
                {
                    b.Property<int>("mediaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAZWA")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OPIS")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("mediaID");

                    b.ToTable("MEDIA");
                });

            modelBuilder.Entity("zadanie2.Program+ODCINKI", b =>
                {
                    b.Property<int>("odcinkiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DLUGOSCODC")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NAZWAANIME")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NAZWAODCINKA")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NRODCINKA")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("odcinkiID");

                    b.ToTable("ODCINKI");
                });

            modelBuilder.Entity("zadanie2.Program+OGLADANE", b =>
                {
                    b.Property<int>("ogladaneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("aniemID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("animeID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("odcinekID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("odcinkiID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("statusID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("tomID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("uzytkownicyID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("uzytkownikID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ogladaneID");

                    b.HasIndex("aniemID");

                    b.HasIndex("odcinkiID");

                    b.HasIndex("statusID");

                    b.HasIndex("tomID");

                    b.HasIndex("uzytkownikID");

                    b.ToTable("OGLADANE");
                });

            modelBuilder.Entity("zadanie2.Program+SEZON", b =>
                {
                    b.Property<int>("sezonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAZWA")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("sezonID");

                    b.ToTable("SEZON");
                });

            modelBuilder.Entity("zadanie2.Program+STATUS", b =>
                {
                    b.Property<int>("statusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAZWA")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("statusID");

                    b.ToTable("STATUS");
                });

            modelBuilder.Entity("zadanie2.Program+TAGI", b =>
                {
                    b.Property<int>("tagiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAZWA")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OPIS")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("tagiID");

                    b.ToTable("TAGI");
                });

            modelBuilder.Entity("zadanie2.Program+TOM", b =>
                {
                    b.Property<int>("tomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DLUGOSCTOMU")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NRTOMU")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("aniemID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("animeID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("tomID");

                    b.HasIndex("aniemID");

                    b.ToTable("TOM");
                });

            modelBuilder.Entity("zadanie2.Program+TWORCA", b =>
                {
                    b.Property<int>("tworcaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DATAURODZENIA")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("IMIENASWISKO")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("tworcaID");

                    b.ToTable("TWORCA");
                });

            modelBuilder.Entity("zadanie2.Program+UZYTKOWNIK", b =>
                {
                    b.Property<int>("uzytkownikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DATAURODZENIA")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NAZWA")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("uzytkownikID");

                    b.ToTable("UZYTKOWNIK");
                });

            modelBuilder.Entity("zadanie2.Program+ANIEM", b =>
                {
                    b.HasOne("zadanie2.Program+MEDIA", null)
                        .WithMany("ANIEMs")
                        .HasForeignKey("mediaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("zadanie2.Program+SEZON", null)
                        .WithMany("ANIEMs")
                        .HasForeignKey("sezonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("zadanie2.Program+TAGI", null)
                        .WithMany("ANIEMs")
                        .HasForeignKey("tagiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("zadanie2.Program+TWORCA", null)
                        .WithMany("ANIEMs")
                        .HasForeignKey("tworcaID");
                });

            modelBuilder.Entity("zadanie2.Program+OGLADANE", b =>
                {
                    b.HasOne("zadanie2.Program+ANIEM", null)
                        .WithMany("OGLADANEs")
                        .HasForeignKey("aniemID");

                    b.HasOne("zadanie2.Program+ODCINKI", null)
                        .WithMany("OGLADANEs")
                        .HasForeignKey("odcinkiID");

                    b.HasOne("zadanie2.Program+STATUS", null)
                        .WithMany("OGLADANEs")
                        .HasForeignKey("statusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("zadanie2.Program+TOM", null)
                        .WithMany("OGLADANEs")
                        .HasForeignKey("tomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("zadanie2.Program+UZYTKOWNIK", null)
                        .WithMany("OGLADANEs")
                        .HasForeignKey("uzytkownikID");
                });

            modelBuilder.Entity("zadanie2.Program+TOM", b =>
                {
                    b.HasOne("zadanie2.Program+ANIEM", null)
                        .WithMany("TOMs")
                        .HasForeignKey("aniemID");
                });
#pragma warning restore 612, 618
        }
    }
}
